---
application_name: 'example'
namespace: 'github.com/nicholasjackson'
generator_name: minke-generator-go
docker_registry:
  url: 
  user: 
  password: 
  email: 
  namespace: 
docker:
  application_docker_file: './dockerfile/example/'
  application_compose_file: './dockercompose/example/docker-compose.yml'
fetch:
  enabled: true
test:
  enabled: true
build:
  post:
    copy:
      -
        from: '../example'
        to: './dockerfile/example'
run:
  consul_loader:
    config_file: './consul_keys.yml'
    url:
      address: consul
      port: 8500
      type: bridge
cucumber:
  consul_loader:
    config_file: './consul_keys.yml'
    url:
      address: consul
      port: 8500
      type: bridge
  health_check:
    address: example
    port: 8001
    path: /v1/health
    type: bridge
shell:
  consul_loader:
    config_file: './consul_keys.yml'
    url:
      address: consul
      port: 8500
      type: bridge
  docker:
    application_docker_file: './dockerfile/example/'
    application_compose_file: './dockercompose/example/docker-compose-no-server.yml'
  ports:
    - "8001:8001"
